In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import os

sns.set

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
#from google.colab import files
#uploaded = files.upload()

In [ ]:
selected_variables = ['Residence_Addresses_Zip',
                      'Residence_Addresses_Latitude',
                      'Residence_Addresses_Longitude',
                      'Residence_Addresses_Density',
                      'Residence_Families_FamilyID',
                      'Residence_Families_HHCount',
                      'Residence_HHGender_Description',
                      'Residence_HHParties_Description',
                      'Parties_Description',
                      'VoterParties_Change_Changed_Party',
                      'Ethnic_Description',
                      'EthnicGroups_EthnicGroup1Desc',
                      'Voters_OfficialRegDate',
                      'US_Congressional_District',
                      'State_Senate_District',
                      'State_House_District',
                      'AddressDistricts_Change_Changed_HD',
                      'County',
                      'CommercialData_DwellingType',
                      'CommercialData_EstimatedHHIncome',
                      'CommercialData_EstimatedHHIncomeAmount',
                      'CommercialData_PresenceOfChildrenCode',
                      'CommercialData_PropertyType']


## Change the file path below accordingly to point toward the relevant file. Note that this data loading step below
## will take the longest out of any step for your computer to process

state_demographic = pd.read_csv('VM2--AK--2020-03-18-DEMOGRAPHIC.tab', 
                                sep='\t', dtype=str, encoding='unicode_escape',
                                usecols=selected_variables)

## Preview of the first 5 rows of the data subset. 

state_demographic.head(5)

  Residence_Addresses_Zip  ... CommercialData_PropertyType
0                   99553  ...                     Unknown
1                   99553  ...                     Unknown
2                   99553  ...                   Apartment
3                   99553  ...                   Apartment
4                   99553  ...                     Unknown

[5 rows x 23 columns]

In [ ]:
state_demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522493 entries, 0 to 522492
Data columns (total 23 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Residence_Addresses_Zip                 522431 non-null  object
 1   Residence_Addresses_Latitude            511827 non-null  object
 2   Residence_Addresses_Longitude           511827 non-null  object
 3   Residence_Addresses_Density             480824 non-null  object
 4   Residence_Families_FamilyID             522493 non-null  object
 5   Residence_Families_HHCount              522493 non-null  object
 6   Residence_HHGender_Description          522493 non-null  object
 7   Residence_HHParties_Description         522493 non-null  object
 8   Parties_Description                     522493 non-null  object
 9   VoterParties_Change_Changed_Party       3663 non-null    object
 10  Ethnic_Description                      455537 non-null  object
 11  EthnicGroups_EthnicGroup1Desc           455537 non-null  object
 12  Voters_OfficialRegDate                  522493 non-null  object
 13  US_Congressional_District               522457 non-null  object
 14  State_Senate_District                   522155 non-null  object
 15  State_House_District                    522106 non-null  object
 16  AddressDistricts_Change_Changed_HD      522490 non-null  object
 17  County                                  522493 non-null  object
 18  CommercialData_DwellingType             422703 non-null  object
 19  CommercialData_EstimatedHHIncome        438750 non-null  object
 20  CommercialData_EstimatedHHIncomeAmount  438752 non-null  object
 21  CommercialData_PresenceOfChildrenCode   333500 non-null  object
 22  CommercialData_PropertyType             522493 non-null  object
dtypes: object(23)
memory usage: 91.7+ MB

In [ ]:
state_demographic.isna().sum()

Residence_Addresses_Zip                       62
Residence_Addresses_Latitude               10666
Residence_Addresses_Longitude              10666
Residence_Addresses_Density                41669
Residence_Families_FamilyID                    0
Residence_Families_HHCount                     0
Residence_HHGender_Description                 0
Residence_HHParties_Description                0
Parties_Description                            0
VoterParties_Change_Changed_Party         518830
Ethnic_Description                         66956
EthnicGroups_EthnicGroup1Desc              66956
Voters_OfficialRegDate                         0
US_Congressional_District                     36
State_Senate_District                        338
State_House_District                         387
AddressDistricts_Change_Changed_HD             3
County                                         0
CommercialData_DwellingType                99790
CommercialData_EstimatedHHIncome           83743
CommercialData_EstimatedHHIncomeAmount     83741
CommercialData_PresenceOfChildrenCode     188993
CommercialData_PropertyType                    0
dtype: int64

In [ ]:
state_sample = state_demographic.sample(frac=0.01)

state_sample.head(5)
state_sample['Residence_Addresses_Latitude'] = pd.to_numeric(state_sample['Residence_Addresses_Latitude']) 
state_sample['Residence_Addresses_Longitude'] = pd.to_numeric(state_sample['Residence_Addresses_Longitude']) 

state_sample.dtypes

Residence_Addresses_Zip                    object
Residence_Addresses_Latitude              float64
Residence_Addresses_Longitude             float64
Residence_Addresses_Density                object
Residence_Families_FamilyID                object
Residence_Families_HHCount                 object
Residence_HHGender_Description             object
Residence_HHParties_Description            object
Parties_Description                        object
VoterParties_Change_Changed_Party          object
Ethnic_Description                         object
EthnicGroups_EthnicGroup1Desc              object
Voters_OfficialRegDate                     object
US_Congressional_District                  object
State_Senate_District                      object
State_House_District                       object
AddressDistricts_Change_Changed_HD         object
County                                     object
CommercialData_DwellingType                object
CommercialData_EstimatedHHIncome           object
CommercialData_EstimatedHHIncomeAmount     object
CommercialData_PresenceOfChildrenCode      object
CommercialData_PropertyType                object
dtype: object

In [ ]:
!pip install -q pyjanitor
# ^^ i commented this out bc i already installed but for the first time just un-comment it out
import janitor

     |████████████████████████████████| 102kB 3.7MB/s

In [ ]:
jittered_lat = state_sample.jitter(
    column_name='Residence_Addresses_Latitude',
    dest_column_name='lat_jitter',
    scale=0.05,
    clip=None,
    random_state=None,
)
jittered_lat.head(5)

       Residence_Addresses_Zip  ...  lat_jitter
221817                   99641  ...   60.898639
327133                   99669  ...   60.495326
73864                    99577  ...   61.351815
95668                    99516  ...   61.063903
305360                   99801  ...   58.338836

[5 rows x 24 columns]

In [ ]:

jittered_long = state_sample.jitter(
    column_name='Residence_Addresses_Longitude',
    dest_column_name='long_jitter',
    scale=0.05,
    clip=None,
    random_state=None,
)

jittered_long.head(5)

       Residence_Addresses_Zip  ...  long_jitter
221817                   99641  ...  -162.056375
327133                   99669  ...  -151.038058
73864                    99577  ...  -149.649700
95668                    99516  ...  -149.689264
305360                   99801  ...  -134.454778

[5 rows x 25 columns]